controller_manager:
  ros__parameters:
    update_rate: 10 # Hz
        
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - wheel_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    allow_integration_in_goal_trajectories: false
    interpolation_method: splines
    open_loop_control: false
    start_with_holding: true
    allow_nonzero_velocity_at_trajectory_end: false
    cmd_timeout: 0.0
    constraints:
      stopped_velocity_tolerance: 1.0
      goal_time: 1.0
      wheel_joint:
        trajectory: 1.0
        goal: 1.0
    gains:
      wheel_joint:
        p: 120.0
        i: 0.0
        d: 30.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
        angle_wraparound: false