controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:
      type: position_controllers/JointGroupPositionController

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

position_controller:
  ros__parameters:
    joints:
      - wheel_joint

velocity_controller:
  ros__parameters:
    joints:
      - wheel_joint
